version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080" # Map your application's port to the host machine
    environment:
      DB_URL: jdbc:mysql://db:3306/mybudgetmanager
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybudgetmanager
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: